services:
  - type: web
    name: babi-kalendar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BASE_URL
        sync: false
